# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5b3db1d6-2769-4f4d-8a72-caa083fd5b74";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5b3db1d6-2769-4f4d-8a72-caa083fd5b74".device = "/dev/disk/by-uuid/5b3db1d6-2769-4f4d-8a72-caa083fd5b74";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8396-F3CD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-2d7ae1cc-e2d1-4efc-a0ca-18edf5894726"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
