{
  description = "sway-home: NixOS config library (lib.mkHost) + installer tools (setup-*)";

  # ONE flake for the whole repo. It exports:
  #   * packages.<system>.default -- the `setup-*` installer tools (used by
  #     the ISO build), wrapping babashka + script-wizard onto PATH.
  #   * lib.mkHost -- builds a nixosSystem for a single host. A per-host repo
  #     (generated by `setup host`) depends on `github:EnigmaCurry/sway-home`
  #     and calls lib.mkHost, passing its own disko.nix/hardware.nix/config.nix.
  #
  # The OS config reaches the whole repo (bashrc, config/, bin/, home-manager/,
  # nixos/modules/) via `self`, so this MUST be a single root flake -- a
  # nixos/-only subdir flake cannot carry those paths into a downstream input.

  inputs = {
    # Single stable nixpkgs for both the installer tools (and ISO) and the
    # NixOS host configuration built by lib.mkHost.
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    nixpkgs_unstable.url = "nixpkgs/nixos-unstable";

    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    disko.url = "github:nix-community/disko";
    disko.inputs.nixpkgs.follows = "nixpkgs";

    nix-flatpak.url = "github:gmodena/nix-flatpak";

    emacs_enigmacurry = { url = "github:EnigmaCurry/emacs"; flake = false; };
    nixos-vm-template = { url = "github:EnigmaCurry/nixos-vm-template"; flake = false; };
    git-prompt = { url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"; flake = false; };
    blog-rymcg-tech = { url = "github:EnigmaCurry/blog.rymcg.tech"; flake = false; };
    script-wizard.url = "github:EnigmaCurry/script-wizard";
    firefox-addons = {
      url = "gitlab:rycee/nur-expressions?dir=pkgs/firefox-addons";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs@{ self, nixpkgs, script-wizard, ... }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);

      # Modules reference `inputs.sway-home` to read repo-root files (bashrc,
      # config/, bin/, ...). With a single root flake, that root IS `self`.
      moduleInputs = inputs // { sway-home = self; };

      # Build a nixosSystem for a single host. Called by a per-host flake:
      #
      #   nixosConfigurations.<name> = sway-home.lib.mkHost {
      #     hostName = "<name>";
      #     userName = "<user>";
      #     system   = "x86_64-linux";          # optional
      #     nixpkgsInput = "nixpkgs";            # optional
      #     profile  = "sway";                   # optional: "sway" | "minimal"
      #     modules  = [ ./disko.nix ./hardware.nix ./config.nix ];
      #     locale   = { timeZone = "..."; ... }; # optional
      #     extraPackages = [ ]; unstablePackages = [ ];  # optional
      #   };
      mkHost = host:
        let
          stableNixpkgs = moduleInputs.${host.nixpkgsInput or "nixpkgs"};
          unstableNixpkgs = moduleInputs.nixpkgs_unstable;
          lib = stableNixpkgs.lib;
          system = host.system or "x86_64-linux";

          unstablePkgs = unstableNixpkgs.legacyPackages.${system};

          hostModules = host.modules or [];
          hostUnstablePackages = host.unstablePackages or [];
          hostExtraPackages = host.extraPackages or [];

          # "sway" (default) = full desktop + home-manager.
          # "minimal" = core only (sshd, no desktop, no home-manager).
          isSway = (host.profile or "sway") == "sway";

          userName = host.userName;
        in
          stableNixpkgs.lib.nixosSystem {
            inherit system;

            specialArgs = {
              inputs = moduleInputs;
              inherit unstablePkgs;
            };

            modules = [
              # disko provides fileSystems/swapDevices from the host's
              # ./disko.nix (the declarative layout from `setup disk`).
              moduleInputs.disko.nixosModules.disko

              ./nixos/modules/unstable-overlay.nix
              ./nixos/modules/host-locale.nix

              ({ ... }: {
                my.host = {
                  locale = host.locale or {};
                };
              })

              ({ ... }: { _module.args.host = host; })
              ({ ... }: { my.unstablePkgs = hostUnstablePackages; })

              ({ pkgs, ... }:
                let
                  toPkgs = names:
                    map (name:
                      if builtins.hasAttr name pkgs
                      then builtins.getAttr name pkgs
                      else throw "mkHost packages: pkgs has no attribute '${name}'"
                    ) names;
                in
                {
                  environment.systemPackages =
                    toPkgs (hostExtraPackages ++ hostUnstablePackages);
                }
              )

              # Core system config (shared by all profiles)
              ./nixos/modules/base.nix
            ]
            # Sway desktop layer -- only for the "sway" profile.
            ++ lib.optional isSway ./nixos/modules/desktop.nix
            # Host-specific modules from the per-host repo
            # (disko.nix + hardware.nix + config.nix).
            ++ hostModules
            ++ [
              { networking.hostName = host.hostName; }

              (import ./nixos/modules/user.nix { inherit userName; })
            ]
            # home-manager is included on EVERY profile so that switching
            # profiles stays fully declarative: a "sway" -> "minimal"
            # downgrade makes home-manager remove the sway dotfiles it no
            # longer manages, instead of orphaning them in $HOME. Only the
            # *content* is gated -- "sway" loads the full desktop
            # environment; "minimal" loads just the essentials (the `admin`
            # alias) so it can also clean up on a downgrade.
            ++ [
              moduleInputs.home-manager.nixosModules.home-manager
              ({ ... }: {
                home-manager = {
                  useGlobalPkgs = true;
                  useUserPackages = true;
                  backupFileExtension = "backup";
                  extraSpecialArgs = { inputs = moduleInputs; inherit userName host; };

                  users.${userName} = { pkgs, ... }:
                    if isSway then
                      let
                        scriptWizard = moduleInputs.script-wizard.packages.${system}.default;
                      in {
                        imports = [ ./home-manager/modules/all.nix ];
                        home.packages = (import ./home-manager/modules/packages.nix { inherit pkgs; }) ++ [ scriptWizard ];
                      }
                    else {
                      imports = [ ./home-manager/modules/minimal.nix ];
                    };
                };
              })
            ];
          };
    in
    {
      lib.mkHost = mkHost;

      packages = forAllSystems (system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
          lib = pkgs.lib;

          # Runtime dependencies the setup-* tools call: babashka to run
          # them and the script-wizard pod for the interactive prompts.
          # disko is intentionally NOT bundled: it needs the network anyway
          # (and so does nixos-install right after), so setup-disk fetches it
          # on demand via `nix run`.
          runtimeDeps = [
            pkgs.babashka
            script-wizard.packages.${system}.default
          ];
        in {
          # Installs each bin/setup*.bb as `setup` / `setup-disk` (the
          # .bb extension stripped), wrapped with runtimeDeps on PATH.
          default = pkgs.stdenvNoCC.mkDerivation {
            pname = "sway-home-installer";
            version = "0.1.0";
            src = ./bin;
            nativeBuildInputs = [ pkgs.makeWrapper ];
            dontConfigure = true;
            dontBuild = true;
            installPhase = ''
              mkdir -p $out/bin
              for f in $src/setup*.bb; do
                name="$(basename "$f" .bb)"
                install -m 0755 "$f" "$out/bin/$name"
                wrapProgram "$out/bin/$name" \
                  --prefix PATH : ${lib.makeBinPath runtimeDeps}
              done
            '';
          };
        });
    };
}
