set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

# print help for Just targets
help:
    @just -l

# Build a customized headless NixOS installer ISO (interactive wizard)
build-iso:
    ./bin/nix_build_iso.bb

# Update this flake's flake.lock (nixpkgs, home-manager, disko, ...)
update:
    nix flake update

# Show flake inputs
metadata:
    nix flake metadata

# NOTE: This repo is now a config LIBRARY (lib.mkHost) + installer tools.
# A machine's own config lives in its per-host repo (~/nixos), generated by
# `setup host` during install, which has its own `just switch`/`test`.

# --- Home Manager (standalone, for non-NixOS systems) ---

# Initial home-manager installation (run once, then use hm-switch)
hm-install: _ensure-git-config
    cd home-manager; nix run home-manager/release-25.11 -- switch --flake .#default --impure -b backup

# Switch home-manager configuration (use on Fedora/other Linux)
hm-switch: _ensure-git-config
    cd home-manager; nix run home-manager -- switch --flake .#default --impure -b backup

# Ensure git local config exists (prompts user if missing)
_ensure-git-config:
    #!/usr/bin/env bash
    set -euo pipefail
    CONFIG_FILE="$HOME/.config/git/config.local"
    if [[ ! -f "$CONFIG_FILE" ]]; then
        echo "Git local config not found. Let's set it up."
        read -rp "Enter your git user.name: " GIT_NAME
        read -rp "Enter your git user.email: " GIT_EMAIL
        mkdir -p "$(dirname "$CONFIG_FILE")"
        cat > "$CONFIG_FILE" << EOF
    [user]
        name = $GIT_NAME
        email = $GIT_EMAIL
    EOF
        echo "Created $CONFIG_FILE"
    fi

# Update home-manager flake.lock
hm-update:
    cd home-manager; nix flake update

# Pull latest changes from remote (resets flake.lock to trust remote)
hm-pull:
    git checkout home-manager/flake.lock 2>/dev/null || true
    git pull

# List home-manager generations
hm-generations:
    home-manager generations

# Rollback to previous home-manager generation
hm-rollback:
    home-manager rollback

# Show home-manager flake inputs
hm-metadata:
    cd home-manager; nix flake metadata

# Show home-manager news
hm-news:
    cd home-manager; nix run home-manager -- news --flake .#default --impure

# Update flake, pull repo, and switch home-manager
hm-upgrade: hm-pull hm-update hm-switch
    @echo ""
    @echo "Run 'hm-news' to read home-manager news."
    @echo "NOTE: Restart your shell to pick up all changes."
    @current=$(grep -oP 'nixpkgs\.url\s*=\s*"github:NixOS/nixpkgs/nixos-\K[0-9]+\.[0-9]+' home-manager/flake.nix); \
    latest=$(git ls-remote --tags https://github.com/NixOS/nixpkgs.git 2>/dev/null \
        | grep -oP 'refs/tags/\K[0-9]+\.[0-9]+$' \
        | sort -t. -k1,1n -k2,2n \
        | tail -1); \
    if [ -n "$latest" ] && [ "$latest" != "$current" ] && [ "$(printf '%s\n%s' "$current" "$latest" | sort -t. -k1,1n -k2,2n | tail -1)" = "$latest" ]; then \
        echo ""; \
        echo ">>> NixOS ${latest} is now available! You are on nixos-${current}."; \
        echo ">>> Update nixpkgs.url in home-manager/flake.nix when ready."; \
    fi
