# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5f5b1c16-b308-4eda-b1ec-0948721f8054";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5f5b1c16-b308-4eda-b1ec-0948721f8054".device = "/dev/disk/by-uuid/5f5b1c16-b308-4eda-b1ec-0948721f8054";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D628-CFE6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-870208a0-81da-419c-9a4b-50b18b2d0710"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
